version: '3'
services:
  db:
    image: postgres:15-alpine
    container_name: my-postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: budget-repo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin