server:
  port: 8000
spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://db:5432/budget-repo
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  #jpa:
  #  generate-ddl: true
  jpa:
    hibernate:
      ddl-auto: update # create-drop -- drop after every restart
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
